name: Convert Latex to PDF
on:
  push:
    branches:
      - 'main'
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@master

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@master
        with:
          root_file: main.tex

      - name: Rename file
        id: rename
        run: mv main.pdf cv.pdf

      - name: Commit generated PDF file
        id: commit
        run: |
          git config --local user.email "action[bot]@github.com"
          git config --local user.name "github-actions[bot]"
          git add cv.pdf
          git commit -m "[ci] updated pdf file"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.CUSTOM_TOKEN }}
