name: Convert Latex to PDF
on:
  push:
    branches:
      - 'main'
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@master

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@master
        with:
          root_file: main.tex

      - name: Rename file
        id: rename
        run: mv main.pdf resume.pdf

      - name: Install ghostscript
        run: sudo apt install ghostscript

      - name: Change ImageMagick security policy
        run: |
          DQT='"' 
          SRC="rights=${DQT}none${DQT} pattern=${DQT}PDF${DQT}"
          RPL="rights=${DQT}read\|write${DQT} pattern=${DQT}PDF${DQT}"
          
          HGT="name=${DQT}height${DQT} value=${DQT}10KP${DQT}"
          HGTR="name=${DQT}height${DQT} value=${DQT}128Kp${DQT}"
          
          WDT="name=${DQT}width${DQT} value=${DQT}10KP${DQT}"
          WDTR="name=${DQT}width${DQT} value=${DQT}128Kp${DQT}"
          
          MAP="name=${DQT}map${DQT} value=${DQT}512MiB${DQT}"
          MAPR="name=${DQT}map${DQT} value=${DQT}4GiB${DQT}"
          
          MEM="name=${DQT}memory${DQT} value=${DQT}256MiB${DQT}"
          MEMR="name=${DQT}memory${DQT} value=${DQT}2GiB${DQT}"
          
          sudo sed -i "s/$SRC/$RPL/" /etc/ImageMagick-6/policy.xml
          sudo sed -i "s/$HGT/$HGTR/" /etc/ImageMagick-6/policy.xml
          sudo sed -i "s/$WDT/$WDTR/" /etc/ImageMagick-6/policy.xml
          sudo sed -i "s/$MAP/$MAPR/" /etc/ImageMagick-6/policy.xml
          sudo sed -i "s/$MEM/$MEMR/" /etc/ImageMagick-6/policy.xml

      - name: Convert PDF to PNG
        run: convert -density 900 -background white -alpha off resume.pdf -resize 25% -quality 90 -colorspace RGB resume.png

      - name: Convert PDF to HTML
        run: docker run --rm -v "`pwd`":/pdf -w /pdf pdf2htmlex/pdf2htmlex:0.18.8.rc2-master-20200820-alpine-3.12.0-x86_64 --zoom 1.3 resume.pdf

      - name: Commit generated PDF file
        id: commit
        run: |
          git config --local user.email "action[bot]@github.com"
          git config --local user.name "github-actions[bot]"
          git add resume.png
          git add resume.pdf
          git add resume.html
          git commit -m "[ci] updated pdf file"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.CUSTOM_TOKEN }}
